CC = cc
CFLAGS = -Wall -Wextra -Werror
NAME = pipex
HEADER = pipex.h

SRCS = $(wildcard *.c) \
	   $(wildcard utils/*.c) \
	   
OBJS = $(SRCS:.c=.o)

all: $(NAME)

$(NAME): $(OBJS)
	@$(CC) $(OBJS) -o $(NAME)
	@echo "Compilation réussie !"
%.o: %.c $(HEADER)
	@$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -f $(OBJS)

fclean: clean
	rm -f $(NAME)

re: fclean all

.PHONY: all clean fclean re
